### ISSUE TITLE
Any plan for a new version with rxpy 3

### ISSUE THREAD

**Issue by jiamo** [PacktPublishing/Hands-On-Reactive-Programming-with-Python#1]
Any plan for a new version with rxpy 3?

**Comment by MainRo** [comment]
I will update the code of the repo in the coming weeks. 
Concerning the book, an update is under discussion by the editor.

**Comment by MainRo** [comment]
All the code is now migrated to rxpy v3 and cyclotron v1. The original code is still available on the ed1/rxpyv1 branch.

**Comment by nlhnt** [comment]
Thanks so much, this book and repository is great to try and create bigger systems with Python :)

**Comment by MainRo** [comment]
Glad that you like it. BTW I will also migrate the code to rxpy v4
