### ISSUE TITLE
Installation instructions update for poetry

### ISSUE THREAD

**Issue by ejm4567** [PacktPublishing/Hands-On-Reactive-Programming-with-Python#3]
Can the install instructions be updated for poetry?

I am trying to install and run the examples in Chapter 12 using poetry.
I've added a section tool.poetry to pyproject.toml in the Chapter 12 cloned git repo for rmux_server

Typing poetry install after adding the missing section tool.poetry yields no error, but then doing the following:
`cd rmux_server
 python3 tcp_server.py`

yields nothing running.

I've not used poetry before, so apologies if this is simple.

**Comment by MainRo** [comment]
Do you see any errors when starting the server? Does It work when installing the package directly with pip?

In the command line that you show, there is a missing && after the cd:

```
cd rmux_server && python3 tcp_server.py
```

Do you know if this is a typo in the comment? Otherwise, the server is not started.
